#!/bin/bash

declare -rA ICON_MAP=(
#     DAY      NIGHT
    ["01d"]=B ["01n"]=C
    ["02d"]=H ["02n"]=I
    ["03d"]=N ["03n"]=N
    ["04d"]=Y ["04n"]=Y
    ["09d"]=R ["09n"]=R
    ["10d"]=X ["10n"]=X
    ["11d"]=P ["11n"]=P
    ["13d"]=W ["13n"]=W
    ["50d"]=J ["50n"]=K
)

declare -r HTTP_OK=200


declare -r WEATHER_APPID="$(cat $HOME/.owm_appid)"
declare -r WEATHER_CITY=$BLOCK_INSTANCE
declare -r WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?q=$WEATHER_CITY&units=metric&type=accurate&APPID=$WEATHER_APPID"
declare -r WEATHER_DATA=$(curl -s $WEATHER_URL)


declare -r RESULT_CODE=$(echo $WEATHER_DATA | jq '.cod')
declare -r TEMPERATURE=$(echo $WEATHER_DATA | jq '.main.temp')
declare -r ICONMAP_KEY=$(echo $WEATHER_DATA | jq -r '.weather[0].icon')


if [ $RESULT_CODE -eq $HTTP_OK ]; then
	echo "<span font_desc='Meteocons Bold'>${ICON_MAP[$ICONMAP_KEY]}</span> $TEMPERATURE °C"
else
	echo " -- °C"
fi
